[workspace]
members = [
    "crates/baad-core",
    "crates/baad",
    "crates/baad-utils",
    "crates/baad-dm",
    "crates/baad-cli"
]
resolver = "2"

[workspace.package]
version = "3.0.0"
edition = "2024"
authors = ["Zinth"]

[workspace.dependencies]
tokio = { version = "1.49", features = ["full"] }
eyre = "0.6"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
reqwest = "0.13"
lazy-regex = "3.5"
strum = { version = "0.27", features = ["derive"] }
bacy = { git = "https://github.com/Deathemonic/BA-CY", version = "3.1.0" }

baad = { path = "crates/baad" }
baad-core = { path = "crates/baad-core" }
baad-utils = { path = "crates/baad-utils" }
baad-dm = { path = "crates/baad-dm" }
