[package]
name = "baad-ffi-build"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
shadow-ffi.workspace = true
shadow-ffi-diplomat.workspace = true
heck.workspace = true
serde_json.workspace = true
sha2 = "0.10"

[lints]
workspace = true
