[package]
name = "baad-utils-ffi"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "baad_utils"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = ["c-api"]
c-api = []
uniffi = ["dep:uniffi", "uniffi/tokio"]
uniffi_cli = ["uniffi/cli"]

[dependencies]
baad-shared = { workspace = true }
baad-utils = { workspace = true, features = ["logs", "observer", "utils"] }
uniffi = { workspace = true, optional = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
baad-ffi-build = { workspace = true }

[[bin]]
name = "uniffi-bindgen"
path = "bindgen.rs"
required-features = ["uniffi/cli"]

[lints]
workspace = true