[package]
name = "baad"
version.workspace = true
edition.workspace = true

[dependencies]
baad-shared = { workspace = true }
baad-utils = { workspace = true }
baad-dm = { workspace = true }

tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
lazy-regex = { workspace = true }
strum = { workspace = true }
bon = { workspace = true }
memorypack = { workspace = true }
bacy = { workspace = true }
tracing = { workspace = true }

walkdir = "2.5.0"
zip = "7.2"
base64 = "0.22"
glob = "0.3"
nucleo = "0.5"
ada-url = "3.4"
rayon = "1.11.0"
memchr = "2.7.6"
urlencoding = "2.1.3"
